### ISSUE TITLE
Sound disappears on iOS 12

### ISSUE THREAD

**Issue by rea-laura** [phetsims/friction#173] opened 2019-02-06 18:52 UTC
<b>Test Device</b>

Leiniz

<b>Operating System</b>

iOS 12.1.3

<b>Browser</b>

Safari 12.1.3

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/282:
Sounds disappears occasionally on iOS devices. Could be related to https://github.com/phetsims/resistance-in-a-wire/issues/190 since it is hard to reproduce and happens irregularly. Observed on other iOS devices (iOS 11). Will update if found on other platforms.

<b>Steps to Reproduce</b>

1) open sim
2) press the reset button. Note there is sound.
3) using the PhET menu, take a screenshot. Screenshot will appear in a new tab in the browser.
4) switch from sim to screenshot tab 15 times in a row
5) close screenshot tab
6) go back to sim and note there is no longer any sound. It cannot be fixed by reloading or turning on/off the sound in the sim. Only a page refresh will fix the issue.

**Comment by rea-laura** [comment] 2019-02-06 19:04
Also happens in published version of resistance in a wire, so probably a browser issue.

**Comment by zepumph** [comment] 2019-02-07 01:34
Let me know if I can help @jbphet.

**Comment by zepumph** [comment] 2019-02-12 01:30
@emily-phet do you think this should hold up publication of Friction?

**Comment by emily-phet** [comment] 2019-02-12 12:56
@zepumph Seems like this "is hard to reproduce and happens irregularly"'. Let's proceed with publishing Friction. 

@jbphet please keep this on your radar - or comment if you think it's not worth investigating, or you have some ideas about it.

**Comment by jbphet** [comment] 2019-02-12 16:33
I'll plan to take a brief look at it after I finish the implementation of the sound for Ohm's Law.  My initial thought it that it's related to some of the other issues we've seen with Safari and the audio context going into the "interrupted" state.

The part of the description where it says:

> switch from sim to screenshot tab 15 times in a row

makes me also feel like this is not a blocking issue.

**Comment by jbphet** [comment] 2019-02-27 21:14
As suspected, the audio context state is being set to "interrupted" when this happens.  I've generalized the handling of post-initialization audio context state changes in https://github.com/phetsims/tambo/commit/1ce0eed0b1556e13bc2acf72833142f1cda666bb, and that appears to have fixed the problem based on some very minimal testing.

Please test this again on master and see if the problem is now gone.  If so, this issue can be closed.

**Comment by KatieWoe** [comment] 2019-02-27 21:29
Attempted several times on iOS 12 master and it seems to be fixed @jbphet

**Comment by jbphet** [comment] 2019-02-28 16:48
Cool.  Closing.

**Closed by jbphet** 2019-02-28 16:48 UTC
Labels: type:bug

**Comment by JustFly1984** [comment] 2019-12-06 14:30
@jbphet  You saved my day, this is the only working solution to fix bugs related to IOS undocumented webkitAudioContext.state === 'interrupted' and Visibility API on Iphone lock/unlock!

**Comment by jbphet** [comment] 2019-12-06 17:43
Glad I could help!
