### ISSUE TITLE
PhET-iO implementation needed

### ISSUE THREAD

**Issue by emily-phet** [phetsims/friction#62] opened 2018-01-23 04:50 UTC
Need phet-io implementation, and sonification wrapper, to advance sound design work.

**Comment by kathy-phet** [comment] 2018-01-24 15:47
OK. 

@samreid - Can you make this your next instrumentation priority? My recollection for our last conversation with @ariel-phet was that we suspected it would be good to begin with a sanity code review to make sure the code was in reasonable shape to move forward with instrumentation (since it was an MLL sim).  Let us know what your priorities look like and if this can fit in. (It seems like the Capacitor Lab: Basics prep work is almost complete (at least for now). I will try to connect with JO today to resolve or at least input into the Capacitor Lab: Basics probe instrumentation issue).

**Comment by samreid** [comment] 2018-01-24 17:50
@emily-phet can you please comment on timeline and what features the sonification team hopes to leverage?

@kathy-phet and @ariel-phet will we have time to do a "Stable PhET-iO" design for this sim before instrumenting it?  It would save us time in the long run.

**Comment by kathy-phet** [comment] 2018-01-24 18:00
I suspect the timeline will require more the "instrument everything reasonable" approach to support the sonification work, but we will see when Emily needs it. 

@samreid - Seems like the code review is needed, regardless, so if you could start on that when you have time, that would be great.

**Comment by emily-phet** [comment] 2018-01-24 18:09
Putting this here, as this is what I could dig up, but would like to confirm with @jbphet that this was the list *after* we discussed it with Mike.

Pickup / drop of book
Contact / no contact between books
Horizontal velocity of book 
Current “temperature”
Break off / exit events (one per molecule)

**Comment by kathy-phet** [comment] 2018-01-24 18:18
Horizontal velocity of book - do you need velocity, or just moving left/right or not moving? I suspect velocity is not a variable in the sim currently.

**Comment by emily-phet** [comment] 2018-01-24 18:37
@kathy-phet JB is offline on slack, so asking Mike to weigh in directly on his needs here. I'll check in with JB next time I notice he's on slack.

**Comment by samreid** [comment] 2018-01-24 21:01
I'm not complaining and happy to help out, but I noticed that @jbphet is listed as Friction's responsible developer in https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md.  Would you like him to take on any part of the code review or instrumentation process?  I'm fine either way, just wanted to double check before I get too far.

**Comment by kathy-phet** [comment] 2018-01-24 21:06
@ariel-phet can weigh in too, but I think we discussed that given current constraints for John and the need to publish this sim with PhET-iO on a shorter timeframe, that we had hoped you would take this on. We were also hoping it was a smaller sim, so not too hard to pick up for reviewing.

**Comment by jbphet** [comment] 2018-01-25 16:41
I've added the SonLab team to this repo so that members of that team can be assigned issues and easily referenced.

**Comment by mikewinters10** [comment] 2018-01-26 21:29
Hi @samreid,

We discussed friction more today in the sonification design meeting. Would it be possible for PhET-iO to include whether the user has selected the macroscopic or microscopic view? To be explicit, whether the user has picked up the book in the bottom (book) view, or the upper (particle) view?

Many thanks, Mike

**Comment by samreid** [comment] 2018-01-27 00:27
Sounds good, thanks @mikewinters10

**Comment by samreid** [comment] 2018-01-31 16:21
> Pickup / drop of book

I think it would be possible (but not optimal) to leverage the event stream for monitoring pickup and drop of the book, but it seems it would be clearer, more robust and more maintainable to have a `dragging` property.  I'm not sure whether to create a new model property, or to convert the  `SimpleDragHandler.dragging` attribute to an instrumented axon Property.  I'll reach out to @jonathanolson to see what he thinks (though I know new scenery listeners are on the horizon).

**Comment by jonathanolson** [comment] 2018-01-31 17:08
A dragging property sounds fine for SimpleDragHandler. Refactoring the dragging getter to use property.value can be avoided by using an ES5 getter.

**Comment by samreid** [comment] 2018-01-31 17:09
Thanks @jonathanolson. Summarizing TODOs:

- [ ] Pickup / drop of book
- [ ] Contact / no contact between books
- [ ] Horizontal velocity of book
- [ ] Current “temperature”
- [ ] Break off / exit events (one per molecule)
- [ ] Distinguish between whether the user has picked up the zoomed in book or zoomed out book

**Comment by samreid** [comment] 2018-01-31 17:11
> Current “temperature”

This is implemented in the sim as "amplitude" and varies between 1 and 8 (or a bit more).  Maybe we should use the value computed for showing the thermometer.

**Comment by emily-phet** [comment] 2018-01-31 17:54
@samreid I don't think we need actual temperature values, just the ability to distinguish at a finer grain level than 8 or 12 values. We're going to have come up with descriptions for different temperature ranges in the sim, and for certain points of interest on the thermometer. Documenting this using indicators that range from 1-100 may be better than 0-1. I'm going to ask @terracoda to comment.

**Comment by samreid** [comment] 2018-01-31 19:53
@emily-phet they are floating point numbers, so there is a wide continuum.  Do you think we need to normalize it, or just provide a way of getting the min (1) and the max (something around 12).

**Comment by samreid** [comment] 2018-02-02 17:59
> Break off / exit events (one per molecule)

I wasn't 100% sure what you meant by exit events.  Do you need a message when a molecule leaves the screen?  Or is it enough to know when it breaks off?

**Comment by samreid** [comment] 2018-02-02 18:13
Initial draft is here: https://www.colorado.edu/physics/phet/dev/html/friction/1.5.0-dev.3/phet-io/wrappers/index

Please see the 5 preceding comments for usage notes and follow-up questions.

**Comment by mikewinters10** [comment] 2018-02-02 21:38
Hi @samreid,

I've done some testing: it looks good! Here's what I've culled from the
instance proxies so far:

   - Pickup / drop of book => isDraggedProperty
   - Contact / no contact between books => contactProperty
   - Horizontal velocity of book => derivable from bookPositionProperty
   - Current “temperature” => amplitudeProperty

Sorry I wasn't clear with "break off/exit events." I just need need a
message every time a molecule breaks off.

I know that it was added late, but we would still like to distinguish if
the user has picked up the zoomed-in or zoomed-out book. I couldn't figure
out how to get it if it was available.

**Comment by samreid** [comment] 2018-02-02 22:10
There are 3 `isDraggedProperty` instances, one is for the macroscopic book, one is for the microscopic book and one is for the area of molecules on the microscopic book.

The `friction.frictionScreen.model.evaporationEmitter` emits an event each time a molecule evaporates from the book.

**Comment by mikewinters10** [comment] 2018-02-02 23:02
Thank you @samReid! I'm getting all the messages now. Here's the complete
mapping:

   - "Macroscopic" pickup /drop =>
   chemistryBookNode.dragHandler.isDraggedProperty
   - "Microscopic" pick up / drop =>
   magnifierNode.backgroundDragHandler.isDraggedProperty
   - Contact / no contact between books => contactProperty
   - Horizontal velocity of book => derivable from bookPositionProperty
   - Current “temperature” => amplitudeProperty
   - Molecule Break-off events => evaporationEmitter

However, counting the messages from
'friction.frictionScreen.model.evaporationEmitter' using the Colin Clark's
phet-osc-bridge, I still receive messages even after no more molecule
break-off events occur visually. In essence, even after all of the
molecules have broken off, if you still rub the books together to maximum
temperature, more evaporationEmitter messages are released. Is there
something additional I should be doing to only see messages when molecules
are breaking off? I know I could just manually suppress after say ~100
molecules, but I'm wondering if there's a way I should be doing it instead.

Many thanks,
Mike

**Comment by samreid** [comment] 2018-02-02 23:05
Good catch, I have reproduced the problem and will work on publishing a new version with a fix.

**Comment by samreid** [comment] 2018-02-03 14:12
I published a new version that only emits evaporation events when an atom evaporates (previous version emitted when the amplitude reached a threshold that would allow atoms to evaporate).

https://www.colorado.edu/physics/phet/dev/html/friction/1.5.0-dev.4/phet-io/wrappers/index/

Also, I noticed that some of the evaporation events are nested in the data stream.  If you are using EmitterIO.addListener (recommended approach) that's great.  If you are monitoring the data stream, you will need to check the entire event tree, not just the top level event.

**Comment by samreid** [comment] 2018-02-03 14:14
Removing assignment while I await feedback, please re-assign the issue to me when feedback is ready.

**Comment by mikewinters10** [comment] 2018-02-05 18:47
Just tested with the phet-osc-bridge, and it is now working as expected =>
91 messages for 91 evaporation events.

Many thanks!

**Comment by samreid** [comment] 2018-02-05 18:48
That's great news!

**Comment by zepumph** [comment] 2018-12-11 22:39
I'm going to close this, phet-io is implemented, and the rest will be sorted out with design-first mentality in #75

**Closed by zepumph** 2018-12-11 22:39 UTC
Labels: dev:phet-io
