### ISSUE TITLE
Random pauses in Legends of Learning harness

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/friction#163] opened 2018-12-21 21:47 UTC
**Test Device**

MacBook Air

**Operating System**

macOS 10.14

**Browser**

Chrome 71.0.3578.98

**Problem Description**

In the Legends of Learning harness, there are random pauses where the sim freezes up for a few seconds and then goes back to normal. It usually happens when you move the book around. (I haven't seen this before, which leads me to believe it's an issue with the sim and not with LoL.)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.5.0-rc.1/phet/friction_en_phet.html
Version: 1.5.0-rc.1 2018-12-20 22:49:42 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"69088d35","branch":"HEAD"},"axon":{"sha":"dd291081","branch":"HEAD"},"brand":{"sha":"b2f1706d","branch":"HEAD"},"chipper":{"sha":"e95d808c","branch":"HEAD"},"dot":{"sha":"8d95f26a","branch":"HEAD"},"friction":{"sha":"72616640","branch":"HEAD"},"joist":{"sha":"64ed222e","branch":"HEAD"},"kite":{"sha":"6c78a24f","branch":"HEAD"},"phet-core":{"sha":"9d80d6a8","branch":"HEAD"},"phet-io":{"sha":"4558068d","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"a066df33","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b19f6689","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"6f3a9e13","branch":"HEAD"},"phet-io-wrappers":{"sha":"9b59dfbc","branch":"HEAD"},"phetcommon":{"sha":"f8c5396f","branch":"HEAD"},"query-string-machine":{"sha":"96ab0c2b","branch":"HEAD"},"scenery":{"sha":"1132d106","branch":"HEAD"},"scenery-phet":{"sha":"4cdcf780","branch":"HEAD"},"sherpa":{"sha":"a1f5e867","branch":"HEAD"},"sun":{"sha":"19bb3f43","branch":"HEAD"},"tambo":{"sha":"e6ea10d9","branch":"HEAD"},"tandem":{"sha":"eb385888","branch":"HEAD"}}
</details>

**Comment by zepumph** [comment] 2018-12-28 20:42
@lmulhall-phet could you give me a bit more explanation. I tried to reproduce with the following link in chrome and firefox (windows10) but didn't see anything pausing through normal use, and even with a lot of book movement. I tested mouse and keyboard.

This is my first time in the LOL harness, so perhaps I'm doing something wrong.

I used this link to mount
http://developers.legendsoflearning.com/public-harness/index.html?questions=1673&startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Ffriction%2F1.5.0-rc.1%2Fphet%2Ffriction_en_phet.html%3FlegendsOfLearning

Here is what the screen looks like to me after I mount and then press "start"

![image](https://user-images.githubusercontent.com/6856943/50527563-a7046a00-0a95-11e9-87fb-ff84f6dd9496.png)

**Comment by lmulhall-phet** [comment] 2019-01-02 19:15
@zepumph, sorry I was a bit too minimalist with the description of the problem. The pauses occur when playing with the simulation in the harness.

**Comment by zepumph** [comment] 2019-01-05 00:05
After again trying to reproduce on my windows 10 with chrome, firefox, and edge, I'm going to assign this over to you @lmulhall-phet until I can get more specifics on what the error looks like and if you can reproduce on other systems.

**Comment by zepumph** [comment] 2019-01-15 03:07
Pinging @lmulhall-phet and @KatieWoe to see if I can get any more assistance in how to reproduce this bug, as it is one of the few issues left before a new RC.

**Comment by KatieWoe** [comment] 2019-01-15 17:45
I just did some testing on Jordan, both 10.13 and 10.14, and wasn't able to reproduce.  When @lmulhall-phet comes in I'll ask him to show me the issue to determine if it is a device issue or if I was missing a step in reproducing it.

**Comment by lmulhall-phet** [comment] 2019-01-15 19:13
@zepumph, it may have been a fluke. I saw it multiple times, but now I can't reproduce on the device I found it on. Sorry about that. I think it's safe for you to ignore this issue.

**Comment by zepumph** [comment] 2019-01-18 01:02
Sounds good. I'm going to close. We can reopen if it comes up again.

**Closed by zepumph** 2019-01-18 01:02 UTC
Labels: type:bug
