### ISSUE TITLE
PhET-iO guide does not exist

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#316] opened 2023-01-02 20:58 UTC
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/868
The link to the PhET-iO Guide leads to a 404 error.

**Comment by zepumph** [comment] 2023-01-04 16:18
Thanks! There was an assumption that you needed an entry in phet-io-sim-specific to get a client guide, but now that is a generated and general resource for all sims, so I updated it so that you don't need a folder in phet-io-sim-specific to get that doc. This is the first sim of the new paradigm. While I was there I also simplified some elements in the process. This is cleanup that probably should have happened around the GAO publication process, but we didn't make the time for it. Now examples are in top level of each sim dir, and that is the only sim-specific file, since we don't need sim-specific images as far as I know.

**Comment by zepumph** [comment] 2023-01-04 16:32
I discussed with @arouinfar and we agree about the current state of creating and maintaining client guides, I updated the README accordingly. I confirmed that friction is getting a phet-io guide now and has examples (the file and a row in the index). Closing

**Closed by zepumph** 2023-01-04 16:32 UTC
Labels: type:bug
