### ISSUE TITLE
Jaws Slow movement causes issues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#166] opened 2019-01-02 20:03 UTC
For https://github.com/phetsims/QA/issues/244
It is a known issue that keyboard nav is significantly slowed down when using Jaws (see: https://github.com/phetsims/john-travoltage/issues/242).  However, this means that it can be hard to build up temperature while using the keys and control is lost after.  It also can cause the same alert to be read out several times (ie. "on far right side, on far right side, etc.").

**Comment by zepumph** [comment] 2019-01-04 22:57
I would like to discuss this with @jessegreenberg, because he has done most of the jaws testing and performance work. Let's talk during dev meeting.

**Comment by jessegreenberg** [comment] 2019-01-04 23:42
Ok, sounds good.

@KatieWoe can you please add any other info about how you were moving the book with JAWS? Arrow keys or WASD keys? Just  to verify, was this on Chrome?

**Comment by KatieWoe** [comment] 2019-01-04 23:44
@jessegreenberg Arrow keys.  Don't think I tried JAWS with WASD now that I think about it.  Yes, Jaws+Chrome

**Comment by jessegreenberg** [comment] 2019-01-05 00:46
OK, thanks. In FF, the arrow keys do not work at all with JAWS because of https://github.com/phetsims/a11y-research/issues/9. Sorry this wasn't in https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit.

I suspect that WASD keys will work better but we haven't checked in on this since we switched to Chrome.

**Comment by jessegreenberg** [comment] 2019-01-07 19:56
I just tested the sim with JAWS in Chrome on my Windows 10 desktop. I was able reproduce the issue on my very fast machine, which makes me think that it is not performance related but caused by https://github.com/phetsims/a11y-research/issues/9.

**Comment by jessegreenberg** [comment] 2019-01-08 16:18
This is probably caused by the default `downDelta` in KeyboardDragListener, which was added for coulombs-law. But it looks like the default drag velocity is a function of this downDelta so setting to zero will set default drag velocity to zero. We don't want that.

**Comment by jessegreenberg** [comment] 2019-01-08 16:54
@zepumph I see these in FrictionKeyboardDragListener, are they needed?
```js
      downDelta: 10,
      shiftDownDelta: 5,
```

**Comment by jessegreenberg** [comment] 2019-01-08 17:37
@zepumph if https://github.com/phetsims/friction/issues/166#issuecomment-452371500 can be removed, this should be fixed in scenery-phet. Verified in a local build of Friction. Here is the SHA you will want:
https://github.com/phetsims/scenery-phet/commit/ea758b228cb70ad582c2e8af1e7c875eabd3f758

**Comment by zepumph** [comment] 2019-01-08 20:06
@jessegreenberg explained this to me in a meeting we just had, and it makes sense to me to remove it. @jessegreenberg can you implement since you will be able to test with jaws.

**Comment by jessegreenberg** [comment] 2019-01-16 16:46
I tried to cherry pick the commits into the release branches but encountered a build error on the 1.5 rc shas. Looks like:
```
Error: ENOENT: no such file or directory, open 'C:\Users\Jesse\Documents\Development\phetsims\perennial\data\not-lintable'
```

Possibly related to https://github.com/phetsims/tasks/issues/972, @zepumph are you familiar with not-lintable?

**Comment by zepumph** [comment] 2019-01-16 18:22
I can take it from here, sorry about the bug. @jessegreenberg says that I need to cherry-pick the following commits:

scenery-phet: https://github.com/phetsims/scenery-phet/commit/ea758b228cb70ad582c2e8af1e7c875eabd3f758

friction: https://github.com/phetsims/friction/commit/c4b16c8a6837e9a575165dfd9c2757034bb897c7

**Comment by zepumph** [comment] 2019-01-17 17:07
We will want to cherry pick https://github.com/phetsims/chipper/commit/4ff287646f7cea993e09b646cdf09cac41e71915 to fix the `not-lintable` bug.

**Comment by zepumph** [comment] 2019-01-26 00:55
These have been cherry-picked locally (mainly a note to myself)

**Comment by jessegreenberg** [comment] 2019-01-28 16:36
I verified that this is fixed in 1.5 with JAWS in Chrome. But it would still be good for QA to verify too.

**Comment by KatieWoe** [comment] 2019-01-30 19:53
While this seems to be fixed when using wasd, the arrow keys don't seem to work at all now when using jaws.

**Comment by KatieWoe** [comment] 2019-01-30 20:12
From slack:
>Michael Kauzmann [12:56 PM]
>I think this is know behavior in jaws. Sometimes they take over the arrow keys.
>That's why we tell people to use WASD.
>Let have @jessegreenberg  confirm, and if that's the case we should make sure to document it somewhere. (edited) 

>Jesse Greenberg [12:57 PM]
>Yes, that is unfortunately the best we can do with JAWS because of https://github.com/phetsims/a11y-research/issues/9

>Kathryn Woessner [12:58 PM]
>Alright.  I'd never seen it before, so I thought it was a new issue.

>Michael Kauzmann [12:58 PM]
>As always, thank you for checking.

>Jesse Greenberg [12:59 PM]
>Indeed, it is very strange, and definitely undesirable.
>It is currently #18 in https://docs.google.com/document/d/12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw/edit

>Kathryn Woessner [12:59 PM]
>Ok
>Thanks

>Michael Kauzmann [1:01 PM]
>Is https://docs.google.com/document/d/12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw/edit meant just for a11y related testing or do you add everything to that? (edited) 

>Jesse Greenberg [1:01 PM]
>It was made just for a11y and is currently only referenced in the a11y sections of the testing templates
>It could be extended though

**Comment by KatieWoe** [comment] 2019-01-31 23:30
Yes

**Closed** 2019-02-01 00:40 UTC
Labels: type:bug
