### ISSUE TITLE
Voicing isn't interrupted when switching between iframes in Multi wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#291] opened 2022-04-05 17:15 UTC
**Test device**
Dell 

**Operating System**
Win10

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/791 in the Multi wrapper, when switching between iframes during an utterance, voicing is not interrupted. Also, if voicing had also been turned on in the second iframe, it will no longer work. I have to refresh the page to get it to work again. 

**Steps to reproduce**
Here is an example:
1. Turn on voicing in the first iframe
2. Go to keyboard shortcuts and click on "Basic Actions"
3. While voicing is reading that section, go to the second iframe and begin to interact with the sim--Voicing will not be interrupted. 

**Visuals**

https://user-images.githubusercontent.com/87318828/161812591-5b8ec37b-2a5b-44aa-8689-5aa999ba0587.mov

**Comment by zepumph** [comment] 2022-07-08 21:24
This is expected behavior. We don't have a lot of control over this because the browser just has one web audio client. I also feel like this isn't too high of a priority since most sims will be used on their own. Closing

**Closed by zepumph** 2022-07-08 21:24 UTC
Labels: type:bug, dev:phet-io, dev:voicing
