### ISSUE TITLE
Dialog state behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#324] opened 2023-01-24 23:42 UTC
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/886.
From Slack:
> Is the preference dialog or the keyboard nav dialog being open meant to be stateful? I thought it wasn't, but it seems to be in friction.

In addition to this, when the state is set, the open dialog sound plays, which seems wrong.

**Steps to Reproduce**
1. Go to the state wrapper
2. Have the state set rate set to every second or so (default works)
3. Open the preferences dialog
4. Observe the downstream sim and note the sound

**Visuals**

https://user-images.githubusercontent.com/41024075/214445596-cc91f1b9-a16b-4914-8b33-877fa745efea.MOV

**Comment by zepumph** [comment] 2023-01-25 03:01
I'll take a look before tossing this one to our resident sound expert.

**Comment by zepumph** [comment] 2023-01-30 18:57
@matthew-blackman and I were able to figure out the problem, but we aren't exactly sure what the best solution is. Basically the sound engine is doing a good job at silencing sound while the state engine is setting state, but in this case, the dialog is being cleared in the "before state set" hook, and that deletion closes dialog, and starts the close sound. 

I would like to implicate @samreid to the next part of this conversation, and will likely discuss in about 5 minutes with him and @matthew-blackman.

**Comment by zepumph** [comment] 2023-01-30 21:21
Fixed by commits over in https://github.com/phetsims/phet-io/issues/1906. Thanks @samreid and @matthew-blackman for helping to get this solved.

**Comment by zepumph** [comment] 2023-01-30 21:32
Wait. I also still hear another problem with the state engine where I hear the very first open sound. I'll keep investigating.

**Comment by jessegreenberg** [comment] 2023-02-08 15:39
OK, 4 commits were cherry-picked from https://github.com/phetsims/phet-io/issues/1906.

![image](https://user-images.githubusercontent.com/6396244/217577057-ffbc868c-1f00-4442-a026-f0ee38524d00.png)

I don't know how to test this one, but opened a dialog in studio in the 1.6 SHAs and pressed "test" and nothing was obviously broken.

Ready to verify.

**Comment by Nancy-Salpepi** [comment] 2023-02-10 22:25
I no longer hear sounds in the downstream sim. 
However, @jessegreenberg  I don't think Katie's original question was ever answered. Is having a dialog open supposed to be stateful? I just compared the behavior in Friction to Beer's Law 1.7.0-rc.2. and it is the same. If that is the intended behavior, then this issue can be closed.

**Comment by jessegreenberg** [comment] 2023-02-10 22:33
I tried to find the answer in https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet-io/doc/guides/phet-io-guide.html#preferences-customization but couldn't find anything specific about the dialog state (just individual preferences). So I believe Dialog's isShowingProperty is meant to be stateful and this is correct.

@arouinfar can you please confirm?

**Comment by arouinfar** [comment] 2023-02-13 17:11
That's correct @jessegreenberg. Every dialog's `isShowingProperty` is stateful, regardless of what type of dialog it is. For Preferences, specifically, `selectedTabProperty` is also stateful. I reviewed the Friction RC and it is behaving as intended, closing.

**Closed by arouinfar** 2023-02-13 17:11 UTC
Labels: type:bug, status:ready-for-review, status:blocks-sim-publication
