### ISSUE TITLE
White flash of screen while manipulating sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#113] opened 2018-09-11 23:23 UTC
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
Seen when confirming https://github.com/phetsims/friction/issues/86
When manipulating the book there are occasional flashes of the screen going white.  It should be noted however that I was unable to recreate this for a screen capture a few minutes later.  This raises the possibility of a hardware issue or me being rather tired and hallucinating a bit.  Documenting just in case.
**Steps to reproduce:**
1. Open sim
2. Using keyboard nav; shift + arrow keys, move book back and forth
3. Seen most often when watching the thermometer

Troubleshooting information (do not edit):

<details>

Name: ‪Friction‬
URL: http://phettest.colorado.edu/friction/friction_en.html?ea&brand=phet
Version: 1.5.0-dev.14 (require.js)
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment] 2018-09-18 20:16
@zepumph, I have not noticed any white flashes.

**Comment by terracoda** [comment] 2018-09-18 20:18
@zepumph, I take it back. If I use the shift key, the blue atoms go white. Maybe that is what @KatieWoe means by a white flash?

**Comment by terracoda** [comment] 2018-09-18 20:21
The white I am seeing might be the intended part of the animation?

**Comment by zepumph** [comment] 2018-09-18 21:32
I can't seem to reproduce. I see white within the blue atoms as the vibrations increase because they are jumping all over the place. It is sort of an optical illusion. I assume that this bug is more than that though.

I tested mainly using the shift key and spamming lots of direction keys. I also tested without the shift keys.

**Comment by terracoda** [comment] 2018-09-18 22:43
@zepumph, if you cannot reproduce the white screen and the white atoms are part of the design, I think you can close this issue.

**Comment by terracoda** [comment] 2018-09-19 18:04
If we can't reproduce this, let's close and re-open if the white flash resurfaces.

**Comment by zepumph** [comment] 2018-09-19 20:58
@KatieWoe can you reproduce this as you originally saw?

**Comment by KatieWoe** [comment] 2018-09-20 18:58
@zepumph I'm not really seeing it anymore.

**Comment by zepumph** [comment] 2018-09-20 18:59
Great, sounds good all around. Closing

**Closed by zepumph** 2018-09-20 18:59 UTC
Labels: type:bug
