### ISSUE TITLE
Keyboard nav instructions can be hidden

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#172] opened 2019-01-31 18:37 UTC
For https://github.com/phetsims/QA/issues/276
When you keyboard focus on one of the books instructions on how to "grab" show up.  Once you grab one time this dialog doesn't appear.  It is possible for this dialog to be hidden with the zoomed in book.  To do this, drag the book to the side with a mouse and then keyboard nav to it.  The dialog stays centered above the book and gets hidden by the edge of the window.  @zepumph says this is intended but may be worth a second look by @terracoda so I'm making this issue here for discussion.
![image from ios](https://user-images.githubusercontent.com/41024075/52076774-a35c7b00-254c-11e9-8cfc-c5f82e648e33.jpg)

**Comment by terracoda** [comment] 2019-02-01 09:50
Please re-assign if you need more comments from me.

**Comment by terracoda** [comment] 2019-02-01 09:53
I'll add, I agree with @zepumph, it is working as intended, and I am not sure at this point that we want to explore making it possible to separate the hint from the focus highlight. In my mind, the naturally go together.

**Comment by emily-phet** [comment] 2019-02-01 20:11
All sounds good to me. Closing.

**Closed by emily-phet** 2019-02-01 20:11 UTC
Labels: type:question
