### ISSUE TITLE
VO repeats descriptions in Wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#286] opened 2022-04-01 12:02 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/791, VoiceOver repeats descriptions in the downstream sim. This only happens for changes made in the sim (moving the book, moving a toggle button on/off). 

**Steps to reproduce**
1. In the state wrapper, set the Set State Rate = 0
2. Make a change in the upstream sim and press 'Set State Now'
3. Turn on VO and tab into the play area of the downstream sim
4. Move book back and forth -- descriptions will repeat

**Visuals**

https://user-images.githubusercontent.com/87318828/161258964-705f1464-3cca-4dad-adc6-a53bcfb3b305.mov

**Comment by Nancy-Salpepi** [comment] 2022-04-01 15:39
Also seen in the following wrappers: Data: textarea, Data: recording, Screenshot, Multi,  and Active wrappers (unable to test studio at this time)

**Comment by zepumph** [comment] 2022-07-15 15:39
I couldn't reproduce this with windows/chrome/nvda. I'll need to solicit a mac user.

**Comment by jessegreenberg** [comment] 2022-07-15 22:04
I was able to reproduce this problem with MacOS 11.6.2 Safari. I tried a basic HTML + js example but could not get this to happen.

index:
<details>

```html
<!doctype html>
<html class="no-js" lang="">
<body>

  <!-- Add your site or application content here -->
  <p>Hello world! This is HTML5 Boilerplate.</p>

  <iframe src="content.html"></iframe>
</body>

</html>

```
</details>

content: 

<details>
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<div>
  <h1>Example iFrame content</h1>
  <p aria-live="polite" id="alerter"></p>
</div>
</body>

<script>
  const alerter = document.getElementById( 'alerter' );

  let counter = 1;

  window.setInterval( () => {
      alerter.textContent = `This is a new alert: ${counter}`;
      counter++;
  }, 5000 );

</script>
</html>
```
</details>

I tried
- aria-live="polite" and aria-live="assertive" to see if one caused it.
- Using the platform workarounds we have in AriaLiveAlerter in our example, so my content.html looks like

<details>

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<div>
  <h1>Example iFrame content</h1>
  <p aria-live="polite" id="alerter"></p>
</div>
</body>

<script>
  const alerter = document.getElementById( 'alerter' );

  let counter = 1;

  window.setInterval( () => {

    setTimeout( () => {
      alerter.textContent = '';

      alerter.hidden = false;

      alerter.textContent = `This is a new alert: ${counter}`;
      counter++;

      window.setTimeout( () => {
        alerter.hidden = true;
      }, 200 );
    } );
  }, 5000 );

</script>
</html>
```

</details>

I am not sure why this is happening in Safari in iFrames but I am not convinced yet that it is not our fault. But I am not sure if we should spend more time on this.

Outside of PhET-iO, I know that embedding PhET sims in iFrames is a popular use case so I am sad that this is broken.

**Comment by zepumph** [comment] 2022-07-26 23:00
@jessegreenberg and I discussed this a bit more. We don't see any potential workarounds, and we don't think it is worth spending more time reproducing the issue at this time. This does not block Friction.

**Comment by zepumph** [comment] 2022-08-05 18:30
@terracoda, @emily-phet, and I think we should create a bug report for this. If any of our third-party embedder of PhET sims reach out with this issue, we can recommend directly using the sim from our website (a bad workaround, but potentially possible).

**Comment by jessegreenberg** [comment] 2022-08-29 21:22
We came back to this today and tried not to 
@jessegreenberg on a Mac 11.6.2 - Could not reproduce this (tested on https://phet-dev.colorado.edu/html/john-travoltage/1.6.4/phet/john-travoltage_all_iframe_phet.html)
@chrisklus on a Mac 10.13.6 Safari 13.1 - Tested (https://phet-dev.colorado.edu/html/john-travoltage/1.6.4/phet/john-travoltage_all_iframe_phet.html)
@Nancy-Salpepi on a Mac 12.5.1, Safar 15.6.1 - It happened immediately in both RAP and JT

Then, @jessegreenberg tried again DID see the problem happen in john-travoltage example. We created some more examples to test on @Nancy-Salpepi machine to see if it will happen outside of PhET. If so we can either identify and fix the problem or submit a bug report to Apple. See examples here: https://phet-dev.colorado.edu/html/jg-tests/iframe-tests/

**Comment by jessegreenberg** [comment] 2022-08-29 21:32
We got it to happen on my machine in the most basic case by doing the following:
- Go to https://phet-dev.colorado.edu/html/jg-tests/iframe-tests/basic/.
- Enter the iframe with the virtual cursor and read the first heading in the content.
- If the aria-live element changes while you are reading the heading with a virtual cursor you will hear the alert content twice.

**Comment by jessegreenberg** [comment] 2022-08-29 21:35
This is about as simple as it gets for aria-live we are ready to submit this example to Apple as a bug report. Since it is outside of our hands we will also make sure it is in the list of known platform issues.

**Comment by zepumph** [comment] 2022-08-29 22:15
Thanks so much to @jessegreenberg @Nancy-Salpepi and @chrisklus for helping to investigate this bug. We couldn't have done it without you all. I'm going to close this issue as a won'tfix knowing that an apple bug report will be given for https://github.com/phetsims/a11y-research/issues/177.

Closing

**Closed by zepumph** 2022-08-29 22:15 UTC
Labels: type:bug, dev:description

**Comment by Nancy-Salpepi** [comment] 2023-01-02 22:03
I know this was closed as "won't fix," but wanted to note that I also see repetition in the Standard Phet-iO wrapper 
in the most recent dev test (https://github.com/phetsims/qa/issues/868).
