### ISSUE TITLE
(Voicing) New overview paragraph mentioning the zoomed-in view

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/friction#195] opened 2021-04-12 22:11 UTC
Added a new last sentence about the zoom-in book.

Warm-up your hands and get ready for Friction! Friction is an interactive sim it changes as you play with it. There’s a stack of big textbooks ready to go! There is a zoomed-in view so you can see how creating friction affects the atoms of the textbooks.

**Comment by terracoda** [comment] 2021-04-13 00:53
@Matthew-Moore240, that's a great start, how about something more active, that makes the zoomed-in view the subject of the sentence. That will eliminate the need for, "There is a", which are not content words, but just required grammatical fluff :-) I made the same change to the previous sentence, eliminating "There's"

"Warm-up your hands and get ready for Friction! Friction is an interactive sim it changes as you play with it. A stack of big textbooks are ready to go! A zoomed-in view shows details of jiggling atoms.

Then on start up the current details will say:
"Chemistry book rests {{lightly}} on top of a Physics book, and is ready to be rubbed against it. In zoomed-in view of where books meet, {{surface temperature thermometer is cool, atoms jiggle a tiny bit}}."

Then if things are active, the overview doesn't change but still sounds good with:
"Chemistry book has {{fewer}} jiggling atoms as {{some}} have broken away. Chemistry book rests {{lightly}} on top of a Physics book. In zoomed-in view of where books meet, {{surface temperature is warm, and dropping as atoms {{jiggle less}}."

In all sentences, the important this is the direct subject of the sentence:
- Friction is
- A stack of big textbooks are
- A zoomed-in view shows
- Chemistry book rests
- surface temperature thermometer is
- etc.

Then the dynamic hint button should hint at grabbing the book, and possibly doing something useful with it depending on whether the "book rests on" or ""rests lightly on" the physics book. If there are not so many atoms left, the hint should encourage reset action.

The content of all three buttons needs to work together at all times, as they can be played together.

**Comment by terracoda** [comment] 2021-04-13 00:58
@Matthew-Moore240, if you like my suggestion, please remove the design-a11y label and assign issue only to @jessegreenberg. That will make it clear to @jessegreenberg the issue is ready for implementation.

**Comment by Matthew-Moore240** [comment] 2021-04-13 18:42
This looks good to me I think shorting it is great. I wasn't 100% sure if just mentioning the zoom-in view was enough.

**Comment by terracoda** [comment] 2021-04-13 19:21
Cool, I agree, we may need more, but I think if we make it the subject of the sentence, it might make it stand out a bit.

**Comment by terracoda** [comment] 2021-04-13 19:23
To sum up for @jessegreenberg, here's the final content for the overview button. It's diffferent from above as I had a grammatical mistake in it.

"Warm-up your hands and get ready for Friction! Friction is an interactive sim it changes as you play with it. A stack of big textbooks is ready to go! A zoomed-in view shows details of jiggling atoms."

**Comment by zepumph** [comment] 2021-07-28 14:55
This is the new and improved overview paragraph in the sim now, and in the design doc:

>Friction is an interactive sim. It changes as you play with it. Warm up your hands and get ready for Friction! There’s a stack of big textbooks ready to go! There is a zoomed-in view so you can see how creating friction affects the atoms of the textbooks.

Closing

**Closed** 2021-07-28 14:55 UTC
Labels: dev:a11y
