### ISSUE TITLE
Dragging book beyond iframe throws off touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#193] opened 2021-04-02 23:01 UTC
Found during https://github.com/phetsims/QA/issues/630 but it happens in published so I don't think it is related. Occurs with iframes and with touch.
When you drag the book up and your finger leaves the iframe the grab point follows it up and stays there as your finger moves back down. This feels quite odd if you try to drag up again with the same touch.

https://user-images.githubusercontent.com/41024075/113460140-ea688400-93d4-11eb-826d-90bad66549c4.MOV

**Comment by zepumph** [comment] 2021-07-23 16:02
@arouinfar, this does not feel like a bug to me, but instead just a byproduct of how something drags against a barrier. You can reproduce this within the sim, with no iframe, just by moving the sim down with your finger continuing to drag past where the books meet. I would recommend closing this issue, but most likely it is up to the responsible designer.

**Comment by zepumph** [comment] 2021-07-23 16:06
UPDATE: Most likely this is due to how the DragListener is just being used to track deltas.  I see how this behavior is strange, but I don't see an obvious way to fix it. @arouinfar, let me know if you would like further investigation.

**Comment by arouinfar** [comment] 2021-07-23 18:59
@zepumph I don't think this needs any further investigation. I don't think this poses any real usability issues, so I'll close.

**Closed by arouinfar** 2021-07-23 18:59 UTC
Labels: status:ready-for-review, type:bug, type:multitouch
