### ISSUE TITLE
(PDOM) Typo (missing space) in screen/scene summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#237] opened 2021-09-21 12:47 UTC
While reviewing Friction, I just noticed that there is a typo (a missing space) in the scene summary. This might be causing a mispronunciation of web speech noted in a different issue.

![friction-typo](https://user-images.githubusercontent.com/1902116/134172610-ba772422-6550-47da-80fe-1434c52b86b8.png)

Please ensure a space exists between "lightly" and "on" when that dynamic phrase is in use.

**Comment by terracoda** [comment] 2021-09-21 12:49
This missing space may be related to one mispronunciation in https://github.com/phetsims/friction/issues/231#issuecomment-920894882

**Comment by terracoda** [comment] 2021-09-21 12:57
Founds some more typos
![friction-typos-more](https://user-images.githubusercontent.com/1902116/134174115-1ffb8484-e5a8-4f48-bb87-bf36ed7a9ee2.png)

We need a space after the period. This correction might also prevent the voicing of "dot" which I have heard a few times, and reported in https://github.com/phetsims/friction/issues/231#issuecomment-920894882.

We also need a space between "thermometer" and "is", which will improve the chance of correct pronunciation there, too.

**Comment by zepumph** [comment] 2021-09-22 15:18
Looks like this is the case for built sims, but not for unbuild:

Unbuilt:

![image](https://user-images.githubusercontent.com/6856943/134371807-927209d4-dc6d-4e3d-b563-911d1c17325d.png)

I think this has to do with our string engine, and how it trims out white space. I will take a look, and see if we have to support this in another way.

**Comment by zepumph** [comment] 2021-09-22 16:21
I reopened https://github.com/phetsims/chipper/issues/619 to discuss this issue in general, and why there weren't assertions occurring. I'll update the friction usages so that this doesn't happen no matter the outcome of that issue.

**Comment by zepumph** [comment] 2021-09-22 16:49
This above commit fixes the problem. @jessegreenberg, would you tell me if this passes code review? I can't think of an easier way to support this. Basically the case is the ability to easily conditionally add words or sentences to other patterns with proper spacing.

**Comment by terracoda** [comment] 2021-09-22 18:30
I found the "dot" case mentioned in https://github.com/phetsims/friction/issues/231#issuecomment-920894882 
It happens after a small break away a sentence is added to the front of the dynamic scene summary.
![friction-typos-period](https://user-images.githubusercontent.com/1902116/134400961-7cd84946-28d3-40b8-8228-60416d708b54.png)

We need a space after the period, before "Chemistry book rests lightly..."

**Comment by terracoda** [comment] 2021-09-22 18:32
@zepumph can you make me a new dev version when you get a chance? I can't seem to load sims from phettest right now.

**Comment by terracoda** [comment] 2021-09-22 18:54
I got to it on phettest finally :-)

The space are fixed and I don't hear the funny pronunciations any more.

Leaving issue open for @jessegreenberg 's review.

**Comment by samreid** [comment] 2021-09-30 18:20
We discussed this a bit in https://github.com/phetsims/chipper/issues/619#issuecomment-931555064, and recommend using more robust patterns for templating strings.  For instance, this line has 2 problematic parts:

```json
      "startingChemistryBookPattern": {
        "value": "{{relativeChemistryBookSentence}}Chemistry book rests {{lightly}}on top of a Physics book, and is ready to be rubbed against it."
      }
```

@pixelzoom asks if:

```json
      "summarySentencePattern": {
        "value": "{{chemistryBookString}} {{jiggleTemperatureScaleSentence}}"
      },
```

should be more general, like a function that combines N sentences, possibly with a template string about how to combine 2 sentences.

**Comment by jessegreenberg** [comment] 2022-02-23 22:50
Back In https://github.com/phetsims/chipper/issues/619#issuecomment-938025193 we confirmed what was described in https://github.com/phetsims/friction/issues/237#issuecomment-931556954 as the recommended way to handle this situation with strings.

Passing back to @zepumph.

**Comment by zepumph** [comment] 2022-03-04 00:57
Excellent thanks. I was able to apply our pattern and had good luck with the regex `}}\w`

Closing

**Closed by zepumph** 2022-03-04 00:57 UTC
Labels: status:blocks-sim-publication, dev:description
